### ISSUE TITLE
feat: deploy js-libp2p bootstrapper

### ISSUE THREAD

**Issue by SgtPooki** [libp2p/js-libp2p-amino-dht-bootstrapper#18]
This issue is tracking the deployment of this bootstrap on our bifrost infra

discussed at https://pl-strflt.notion.site/mob-create-js-libp2p-based-Amino-DHT-bootstrapper-e7793d5a79764df6a08dbc0474935c4d?pvs=4

```[tasklist]
### Tasks
- [x] Initial alpha deployment https://github.com/libp2p/js-libp2p-amino-dht-bootstrapper/pull/135
- [ ] https://github.com/libp2p/js-libp2p-amino-dht-bootstrapper/issues/137
- [x] Get a domain name
- [x] deploy with terraform and add to waterworks monitoring
- [x] ~feat: Add wss listening support~  won't do since it'll be handled by a reverse proxy
- [ ] figure out why tcp listen port closes external connections early
- [x] set agent to be the `js-libp2p-amino-dht-bootstrapper`
- [x] Add ping protocol
- [ ] Figure out why memory use is slowly increasing
- [x] investigate why health-check starts showing unhealthy after a bit
```

**Comment by SgtPooki** [comment]
unassigning this so I can stay focused on Helia and IPFS stuff

**Comment by dhuseby** [comment]
@cayman was going to try to deploy on chainsafe infra but got stalled.

**Comment by dhuseby** [comment]
@SgtPooki to deploy a bootstrapper on sgtpooki.com

**Comment by SgtPooki** [comment]
it could use some robustness and productionization, but it's deployed:

```
╰─ ✔ ❯ ./vole libp2p identify /ip4/147.75.198.229/tcp/4003/ws/p2p/12D3KooWQgrExcg6dkCdiTER3G3ARe14PZ4cLhinKtRcLHsvnk1Q                                  14.88   17.1G   64%   78%  ─╯
PeerID: "12D3KooWQgrExcg6dkCdiTER3G3ARe14PZ4cLhinKtRcLHsvnk1Q"
Protocol version: "ipfs/0.1.0"
Agent version: "libp2p/1.5.1 UserAgent=v20.13.0"
Listen addresses:
	- "/ip4/147.75.198.229/tcp/4001/p2p/12D3KooWQgrExcg6dkCdiTER3G3ARe14PZ4cLhinKtRcLHsvnk1Q"
	- "/ip4/147.75.198.229/tcp/4003/ws/p2p/12D3KooWQgrExcg6dkCdiTER3G3ARe14PZ4cLhinKtRcLHsvnk1Q"
Protocols:
	- "/ipfs/id/1.0.0"
	- "/ipfs/id/push/1.0.0"
	- "/ipfs/kad/1.0.0"
	- "/libp2p/autonat/1.0.0"
	- "/libp2p/circuit/relay/0.2.0/hop"
	- "/webrtc-signaling/0.0.1"
```

Fixed by https://github.com/libp2p/js-libp2p-amino-dht-bootstrapper/pull/135

**Comment by SgtPooki** [comment]
I got some graphs using the metrics dashboards from helia-http-gateway:


<img width="2093" alt="image" src="https://github.com/libp2p/js-libp2p-amino-dht-bootstrapper/assets/1173416/90fe0733-9d61-4676-9846-fdcfb08c87d7">

<img width="2194" alt="image" src="https://github.com/libp2p/js-libp2p-amino-dht-bootstrapper/assets/1173416/cc7766c8-b5d6-4682-bec7-4bdc943c9a9a">

<img width="2195" alt="image" src="https://github.com/libp2p/js-libp2p-amino-dht-bootstrapper/assets/1173416/ffdd27b4-1f8d-4e6e-8cdf-17d5f01897de">

**Comment by SgtPooki** [comment]
graph of last 24 hours (not full because it was only started yesterday afternoon) seems to show steadily increasing memory.

<img width="1934" alt="image" src="https://github.com/libp2p/js-libp2p-amino-dht-bootstrapper/assets/1173416/cd956850-c4b6-4a05-b3b5-029a6940b0b8">

**Comment by achingbrain** [comment]
Does it need autonat?  We can pre-configure it with public `announce` addresses, right?

**Comment by SgtPooki** [comment]
yea I had autonat disabled at first, but enabled it when docker wasn't working with port publishing, and then just left it when switching to `--network host`

here's nodejs metrics from the same helia-http-gateway dashboards (`-old` is the blue increasing line):

<img width="1939" alt="image" src="https://github.com/libp2p/js-libp2p-amino-dht-bootstrapper/assets/1173416/c37893ec-887c-4e2a-b93a-e53145003a94">

**Comment by SgtPooki** [comment]
FYI @achingbrain it looks like they may be correlated with TCP listener errors?

<img width="1538" alt="image" src="https://github.com/libp2p/js-libp2p-amino-dht-bootstrapper/assets/1173416/f5c0e5b4-ce5b-4c10-adaf-f132ccb2c428">

**Comment by 2color** [comment]
Weirdly, I can resolve the peerID from the delegated routing endpoint: https://delegated-ipfs.dev/routing/v1/peers/12D3KooWQgrExcg6dkCdiTER3G3ARe14PZ4cLhinKtRcLHsvnk1Q

**Comment by SgtPooki** [comment]
> Weirdly, I can resolve the peerID from the delegated routing endpoint: [delegated-ipfs.dev/routing/v1/peers/12D3KooWQgrExcg6dkCdiTER3G3ARe14PZ4cLhinKtRcLHsvnk1Q](https://delegated-ipfs.dev/routing/v1/peers/12D3KooWQgrExcg6dkCdiTER3G3ARe14PZ4cLhinKtRcLHsvnk1Q)

Can or cannot? It's only returning `{"Peers":null}` for me right now, but some of the [DHT provide issues Alex recently fixed](https://github.com/libp2p/js-libp2p/issues/2517#issuecomment-2098800835) (talked about during Helia WG) may be related?

If "can" is correct, why is that weird?

**Comment by 2color** [comment]
Sharing an update here for public visibility:

- We're deployed the bootstrapper to va1.bootstrap.libp2p.io
- As part of that deployment, `wss` TLS termination will be handled by Caddy that will then reverse proxy to the node.js process
- We figured out that some connections are reject external connections early, it was due to the connection manager. https://github.com/libp2p/js-libp2p-amino-dht-bootstrapper/pull/147 adds the ability to tune the connection manager config
- https://github.com/libp2p/js-libp2p-amino-dht-bootstrapper/pull/148 should fix the health check problem

**Comment by 2color** [comment]
@achingbrain I just deployed the latest main https://github.com/libp2p/js-libp2p-amino-dht-bootstrapper/commit/5ad7d04883aa2732f4d0ab096a30c8677d3fcebf

**Comment by achingbrain** [comment]
Closing as this is now deployed
